apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mern-frontend
spec:
  defaultBackend:
    service:
      name: helloworld
      port:
        number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mern-frontend
  labels:
    app: mern-frontend
    service: mern-frontend
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: mern-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-frontend
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-frontend
      version: v1
  template:
    metadata:
      labels:
        app: mern-frontend
        version: v1
    spec:
      containers:
      - name: helloworld
        image: jimsheldon/mernfrontend:cf2030bb
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
